# Generated by Django 4.0.4 on 2022-05-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=255)),
                ('lecture_url', models.CharField(max_length=255)),
                ('embed_url', models.CharField(max_length=255)),
                ('lecture_note', models.TextField()),
                ('lecture_sum', models.TextField()),
                ('keyword', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caffeine.users')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lecturehistory',
            constraint=models.UniqueConstraint(fields=('lecture_id', 'lecture_name'), name='lecture_id_and_name'),
        ),
    ]
